In [1]:
import pandas as pd

In [2]:
file= "Resources/state-freq-data.csv"
weather_df=pd.read_csv(file, skiprows=[0], index_col="state")
weather_df

,year,drought,flooding,freeze,severe storm,tropical cyclone,wildfire,winter storm
state,,,,,,,,
AK,1980,0,0,0,0,0,0,0
AL,1980,1,0,0,0,0,0,0
AR,1980,1,1,0,0,0,0,0
AZ,1980,0,0,0,0,0,0,0
CA,1980,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
VT,2020,0,0,0,0,0,0,0
WA,2020,1,0,0,0,0,1,0
WI,2020,0,0,0,3,0,0,0
WV,2020,0,0,0,3,0,0,0
WY,2020,1,0,0,0,0,1,0

In [3]:
weather_df.to_csv('Resources/clean_weather.csv')